version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "auto"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "auto"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "auto"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
